//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaleGhent.NINA.AstroPhysics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Astro-Physics\\APCC Pro\\ApPointMapper.exe")]
        public string APPMExePath {
            get {
                return ((string)(this["APPMExePath"]));
            }
            set {
                this["APPMExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APPMSettingsPath {
            get {
                return ((string)(this["APPMSettingsPath"]));
            }
            set {
                this["APPMSettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APPMMapPath {
            get {
                return ((string)(this["APPMMapPath"]));
            }
            set {
                this["APPMMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApccExePath {
            get {
                return ((string)(this["ApccExePath"]));
            }
            set {
                this["ApccExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public uint ApccStartupTimeout {
            get {
                return ((uint)(this["ApccStartupTimeout"]));
            }
            set {
                this["ApccStartupTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Astro-Physics\\APCC Standard\\AstroPhysicsCommandCenter.exe")]
        public string ApccDefaultStandardPath {
            get {
                return ((string)(this["ApccDefaultStandardPath"]));
            }
            set {
                this["ApccDefaultStandardPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Astro-Physics\\APCC Pro\\AstroPhysicsCommandCenter.exe")]
        public string ApccDefaultProPath {
            get {
                return ((string)(this["ApccDefaultProPath"]));
            }
            set {
                this["ApccDefaultProPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint ApccDriverConnectTimeout {
            get {
                return ((uint)(this["ApccDriverConnectTimeout"]));
            }
            set {
                this["ApccDriverConnectTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DecArcRaSpacing {
            get {
                return ((int)(this["DecArcRaSpacing"]));
            }
            set {
                this["DecArcRaSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DecArcDecSpacing {
            get {
                return ((int)(this["DecArcDecSpacing"]));
            }
            set {
                this["DecArcDecSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DecArcHourAngleLeadIn {
            get {
                return ((double)(this["DecArcHourAngleLeadIn"]));
            }
            set {
                this["DecArcHourAngleLeadIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DecArcQuantity {
            get {
                return ((int)(this["DecArcQuantity"]));
            }
            set {
                this["DecArcQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DecArcPointOrderingStrategy {
            get {
                return ((int)(this["DecArcPointOrderingStrategy"]));
            }
            set {
                this["DecArcPointOrderingStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int DecArcPolarProximityLimit {
            get {
                return ((int)(this["DecArcPolarProximityLimit"]));
            }
            set {
                this["DecArcPolarProximityLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DecArcPolarPointOrderingStrategy {
            get {
                return ((int)(this["DecArcPolarPointOrderingStrategy"]));
            }
            set {
                this["DecArcPolarPointOrderingStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyCreateWestPoints {
            get {
                return ((bool)(this["AllSkyCreateWestPoints"]));
            }
            set {
                this["AllSkyCreateWestPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyCreateEastPoints {
            get {
                return ((bool)(this["AllSkyCreateEastPoints"]));
            }
            set {
                this["AllSkyCreateEastPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppmSetSlewRate {
            get {
                return ((bool)(this["AppmSetSlewRate"]));
            }
            set {
                this["AppmSetSlewRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int AppmSlewRate {
            get {
                return ((int)(this["AppmSlewRate"]));
            }
            set {
                this["AppmSlewRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AppmSlewSettleTime {
            get {
                return ((int)(this["AppmSlewSettleTime"]));
            }
            set {
                this["AppmSlewSettleTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyUseMeridianLimits {
            get {
                return ((bool)(this["AllSkyUseMeridianLimits"]));
            }
            set {
                this["AllSkyUseMeridianLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyUseHorizonLimits {
            get {
                return ((bool)(this["AllSkyUseHorizonLimits"]));
            }
            set {
                this["AllSkyUseHorizonLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AppmZenithSafetyDistance {
            get {
                return ((double)(this["AppmZenithSafetyDistance"]));
            }
            set {
                this["AppmZenithSafetyDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double AppmZenithSyncDistance {
            get {
                return ((double)(this["AppmZenithSyncDistance"]));
            }
            set {
                this["AppmZenithSyncDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AllSkyPointOrderingStrategy {
            get {
                return ((int)(this["AllSkyPointOrderingStrategy"]));
            }
            set {
                this["AllSkyPointOrderingStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AllSkyDeclinationSpacing {
            get {
                return ((int)(this["AllSkyDeclinationSpacing"]));
            }
            set {
                this["AllSkyDeclinationSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AllSkyDeclinationOffset {
            get {
                return ((int)(this["AllSkyDeclinationOffset"]));
            }
            set {
                this["AllSkyDeclinationOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyUseMinDeclination {
            get {
                return ((bool)(this["AllSkyUseMinDeclination"]));
            }
            set {
                this["AllSkyUseMinDeclination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyUseMaxDeclination {
            get {
                return ((bool)(this["AllSkyUseMaxDeclination"]));
            }
            set {
                this["AllSkyUseMaxDeclination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-85")]
        public int AllSkyMinDeclination {
            get {
                return ((int)(this["AllSkyMinDeclination"]));
            }
            set {
                this["AllSkyMinDeclination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int AllSkyMaxDeclination {
            get {
                return ((int)(this["AllSkyMaxDeclination"]));
            }
            set {
                this["AllSkyMaxDeclination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AllSkyRightAscensionSpacing {
            get {
                return ((int)(this["AllSkyRightAscensionSpacing"]));
            }
            set {
                this["AllSkyRightAscensionSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyUseMinHourAngleEast {
            get {
                return ((bool)(this["AllSkyUseMinHourAngleEast"]));
            }
            set {
                this["AllSkyUseMinHourAngleEast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllSkyUseMaxHourAngleWest {
            get {
                return ((bool)(this["AllSkyUseMaxHourAngleWest"]));
            }
            set {
                this["AllSkyUseMaxHourAngleWest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public double AllSkyMinHourAngleEast {
            get {
                return ((double)(this["AllSkyMinHourAngleEast"]));
            }
            set {
                this["AllSkyMinHourAngleEast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double AllSkyMaxHourAngleWest {
            get {
                return ((double)(this["AllSkyMaxHourAngleWest"]));
            }
            set {
                this["AllSkyMaxHourAngleWest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppmUseMinAltitude {
            get {
                return ((bool)(this["AppmUseMinAltitude"]));
            }
            set {
                this["AppmUseMinAltitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int AppmMinAltitude {
            get {
                return ((int)(this["AppmMinAltitude"]));
            }
            set {
                this["AppmMinAltitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AllSkyRightAscensionOffset {
            get {
                return ((int)(this["AllSkyRightAscensionOffset"]));
            }
            set {
                this["AllSkyRightAscensionOffset"] = value;
            }
        }
    }
}
