//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaleGhent.NINA.AstroPhysics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Astro-Physics\\APCC Pro\\ApPointMapper.exe")]
        public string APPMExePath {
            get {
                return ((string)(this["APPMExePath"]));
            }
            set {
                this["APPMExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APPMSettingsPath {
            get {
                return ((string)(this["APPMSettingsPath"]));
            }
            set {
                this["APPMSettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APPMMapPath {
            get {
                return ((string)(this["APPMMapPath"]));
            }
            set {
                this["APPMMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApccExePath {
            get {
                return ((string)(this["ApccExePath"]));
            }
            set {
                this["ApccExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public uint ApccStartupTimeout {
            get {
                return ((uint)(this["ApccStartupTimeout"]));
            }
            set {
                this["ApccStartupTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Astro-Physics\\APCC Standard\\AstroPhysicsCommandCenter.exe")]
        public string ApccDefaultStandardPath {
            get {
                return ((string)(this["ApccDefaultStandardPath"]));
            }
            set {
                this["ApccDefaultStandardPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Astro-Physics\\APCC Pro\\AstroPhysicsCommandCenter.exe")]
        public string ApccDefaultProPath {
            get {
                return ((string)(this["ApccDefaultProPath"]));
            }
            set {
                this["ApccDefaultProPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint ApccDriverConnectTimeout {
            get {
                return ((uint)(this["ApccDriverConnectTimeout"]));
            }
            set {
                this["ApccDriverConnectTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DecArcRaSpacing {
            get {
                return ((int)(this["DecArcRaSpacing"]));
            }
            set {
                this["DecArcRaSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DecArcDecSpacing {
            get {
                return ((int)(this["DecArcDecSpacing"]));
            }
            set {
                this["DecArcDecSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HourAngleLeadIn {
            get {
                return ((double)(this["HourAngleLeadIn"]));
            }
            set {
                this["HourAngleLeadIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DecArcQuantity {
            get {
                return ((int)(this["DecArcQuantity"]));
            }
            set {
                this["DecArcQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PointOrderingStrategy {
            get {
                return ((int)(this["PointOrderingStrategy"]));
            }
            set {
                this["PointOrderingStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int PolarProximityLimit {
            get {
                return ((int)(this["PolarProximityLimit"]));
            }
            set {
                this["PolarProximityLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PolarPointOrderingStrategy {
            get {
                return ((int)(this["PolarPointOrderingStrategy"]));
            }
            set {
                this["PolarPointOrderingStrategy"] = value;
            }
        }
    }
}
